type:docs:
  - "docs/**"
  - ".github/*.md"
area:dependencies:
  - "package.json"
  - "pnpm-lock.yaml"
  - "yarn.lock"
type:maintenance:
  - ".gitmodules"
  - "functions/**"
  - "profile/**"
  - "src/**"
  - "lib/**"
  - ".editorconfig"
  - ".github/CODEOWNERS"
  - ".github/*.md"
  - ".github/*.yml"
  - ".github/*.json"
  - ".imgbotconfig"
  - ".hadolint.y*"
  - ".vscode/*"
  - "tsconfig.json"
  - "babel.config.js"
  - "docusaurus.config.js"
  - "crowdin.yml"
  - "netlify.toml"
  - ".prettierrc"
  - ".prettierignore"
  - ".markdownlint.json"
  - ".trunk/*.yaml"
  - ".trunk/*.json"
  - ".trunk/*rc"
area:ci:
  - ".github/workflows/**"
area:plugin:
  - "functions/**"
  - "*.zsh"
